Medium: Xen: fix regression with xm and quoting (lf#2671)
The latest xl management tool is squeamish about some
characters in a name (the vm name is xen-f):

/etc/xen/vm/xen-f:15: config parsing error near `xen':
syntax error, unexpected IDENT, expecting STRING or NUMBER or '['
/etc/xen/vm/xen-f:15: config parsing error near `-f': lexical error
warning: Config file looks like it contains Python code.
warning:  Arbitrary Python is no longer supported.
warning:  See http://wiki.xen.org/wiki/PythonInXlConfig
Failed to parse config: Invalid argument

The older xm management tool cannot digest quotes:

root@xfc0:~# xm create /shared/domu/test1.cfg name=\"test1\"
Using config file "/shared/domu/test1.cfg".
Error: Invalid VM Name