[PATCH] Use sys/types.h instead of asm/types.h in configure(.in) #include <sys/types.h> instead of <asm/types.h> in the configure theck for icmpv6.h to make sure that __attribute_used__ is present, which is needed indirectly.
This does seem to be correct to me, but there is always the chance
of a regression, so feedback would be appreciated

Observed with /usr/include/linux/icmpv6.h supplied by
linux-libc-dev 2.6.21-2 on ia64 Debian (unstable)

configure:30482: gcc -std=gnu99 -c -g -O2  -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -I/usr/include/libxml2 conftest.c >&5
In file included from /usr/include/asm/intrinsics.h:18,
                 from /usr/include/asm/byteorder.h:10,
                 from /usr/include/linux/icmpv6.h:4,
                 from conftest.c:77:
/usr/include/asm/gcc_intrin.h:26: error: expected ',' or ';' before '__attribute _used__'

Signed-off-by: Simon Horman <horms@verge.net.au>

--HG--
extra : convert_revision : 3dea186a3b19cf5d358def5e454a3793aec0e977